### ISSUE TITLE
Upgrade Django

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#10]
Django 1.11 upgrade before doing Python 3 (see #9)

Meeting notes: https://hackmd.io/JNppGNsdQkC1nkKwJhkoFA?both

Amy's notes: links to Amy's doc https://docs.google.com/document/d/1B16KXGHnxqi-U64Il3WIzB0FDMWDsl8G-fc0Um2LSyQ/edit#

**Comment by marisastrong** [comment]
There are a few items that need to be addressed for upgrading the EZID Django application.

- [ ] Migrate source code from hg to git
- [ ] Migrate source code from Bitbucket to Github
- [ ] Understand current state of code, define versions to migrate to (meeting scheduled 9/6)

**Comment by mariagould** [comment]
links to Amy's doc https://docs.google.com/document/d/1B16KXGHnxqi-U64Il3WIzB0FDMWDsl8G-fc0Um2LSyQ/edit#

**Comment by mariagould** [comment]
Closing this issue as we are addressing it in sustainability project.
