### ISSUE TITLE
Migrate from mercurial to git

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/ezid-service#100]
<img width="408" alt="Screen Shot 2020-01-13 at 12 38 08 PM" src="https://user-images.githubusercontent.com/19696935/72290231-93289900-3601-11ea-87f8-4f7d94058272.png">

Repositories needing this migration:

- [x] ezid
- [x] ezid-config
- [x] ezid-info-pages

**Comment by rushirajnenuji** [comment]
Hey @mariagould  - I've migrated 4 repositories:
- [ezid](https://github.com/CDLUC3/ezid)
- [ezid-config](https://github.com/CDLUC3/ezid-config)
- [ezid-info](https://github.com/CDLUC3/ezid-info)
- [shoulders](https://github.com/CDLUC3/shoulders)

It would be great if you could have a look at it and let me know your thoughts. Thank you!

**Comment by mariagould** [comment]
Thanks @rushirajnenuji 

Looks good in terms of setup - my only suggestion would be to rename the `shoulders` repo to `ezid-shoulders` so it matches the others and so all of the repos have "ezid" in the name.

**Comment by rushirajnenuji** [comment]
yes, agree on the naming convention. That change is now complete.

**Comment by rushirajnenuji** [comment]
Though the migration is successfully complete - one additional task is to point all the repositories to `.git` upstream.

**Comment by rushirajnenuji** [comment]
The repositories `ezid` and `ezid-info` are pointing to the git upstream on staging and in produciton. 

TODO:

- [ ] `ezid-config` (this is a big task! might take a bit of thought.)
- [ ] `ezid-shoulder`

**Comment by marisastrong** [comment]
@mreyescdl has granted me access to the Merritt Collection Hg Rhodecode repositories, where we have archived all the Mecurial/Hg reposistories.  I will need @rushirajnenuji to zip up the EZID repos from bitbucket, place them somewhere I can access the files and submit them to Merritt.

- [ ] upload zipped up EZID repos for archiving to https://merritt.cdlib.org/m/cdl_uc3_hg_repos

**Comment by mariagould** [comment]
@marisastrong just checking in on status - were you able to take the zipped files and submit them to Merritt?

**Comment by marisastrong** [comment]
The Mecurial repositories from Bitbucket have been archived into the Merritt Collection CDL UC3 Rhodecode Repositories (private collection where other Mecurial repos are archived). 

[https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm56166vj](https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm56166vj)
[https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5285g47
](https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5285g47
)[https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm59s6zkk
](https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm59s6zkk
)[https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5fj7qdn
](https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5fj7qdn
)
