### ISSUE TITLE
Investigate issues with DataCite comparison job

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/ezid-service#101]
The DataCite comparison job is continuing to flag differences that do not appear to be differences. We need to determine why these are being flagged and update the comparison job so that it does not flag the wrong things.

DataCite has confirmed that the DOIs flagged in the check do not seem to present any issues in their system. From Richard Hallett:

> I can't see any issues with any of the above dois, they all appear to match the registered handle system, you can always check the global handle system directly at http://hdl.handle.net/

If we are unable to determine the reason for the inaccurate results, consult with Greg Janee for further guidance. 

**Example results:**
 
**doi:10.17610/T6W899**
We are getting an error notice that there is a “target URL mismatch in Handle system.” This notice flags a discrepancy between
http://escholarship.org/uc/item/60q3d3fd (which is the current designated target in both EZID and DataCite, as far as I can tell) and https://ezid.cdlib.org/id/doi:10.17610/T6W899, which is not the current target. 
 
**doi:10.18739/A2028PD8D**
We are getting a notice that this DOI is not found in DataCite. However, it is, in fact, available in DataCite search and API. 
 
**doi:10.21239/V9K59K**
We are getting a notice that there is a metadata mismatch and target URL mismatch in Handle System (similar to the first example). However, there appear to be no mismatches.
 
Prior reference: #32

**Comment by mariagould** [comment]
Closing as we have put comparison jobs on indefinite hiatus.
