### ISSUE TITLE
Create new shoulder: UCI Department of Computer Science

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#104]
**Form data**
EZID prefix/shoulder: doi:10.24432/C5
Account/organization username (login): uci-cs
Shoulder display name: UCI Department of Computer Science
Datacenter: CDL.UCI

**Steps (once request has been received and triaged by Maria)**
- [x] (Rushiraj) Run "Procedure for adding, modifying, and installing shoulders" as documented in README
- [x] (Rushiraj) Assign issue to Maria when procedure is complete
- [x] (Maria) Add new shoulder to appropriate group
- [x] (Maria) Set up new user account if applicable
- [x] (Maria) Give user account access to shoulder
- [x] (Maria) Notify user that shoulder is ready for use

**Comment by rushirajnenuji** [comment]
@mariagould  - this is ready as well...
