### ISSUE TITLE
Create new shoulder: Center for Effective Global Action

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#105]
**Form data**
EZID prefix/shoulder: doi:10.26085/C3
Account/organization username (login): cega
Shoulder display name: The Center for Effective Global Action
Datacenter: CDL.UCB

**Steps (once request has been received and triaged by Maria)**
- [x] (Rushiraj) Run "Procedure for adding, modifying, and installing shoulders" as documented in README
- [x] (Rushiraj) Assign issue to Maria when procedure is complete
- [x] (Maria) Add new shoulder to appropriate group
- [x] (Maria) Set up new user account if applicable
- [x] (Maria) Give user account access to shoulder
- [x] (Maria) Notify user that shoulder is ready for use

**Comment by mariagould** [comment]
@rushirajnenuji this new shoulder request is ready for you

**Comment by rushirajnenuji** [comment]
@mariagould  - installation complete.
