### ISSUE TITLE
Create new shoulder: University of Illinois Chicago Digital Collections

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#108]
**Form data**
EZID prefix/shoulder: ark:/81984/d3
Account/organization username (login): uic
Shoulder display name: University of Illinois Chicago Digital Collections
Datacenter: 

**Steps (once request has been received and triaged by Maria)**
- [x] (Rushiraj) Run "Procedure for adding, modifying, and installing shoulders" as documented in README
- [x] (Rushiraj) Assign issue to Maria when procedure is complete
- [x] (Maria) Add new shoulder to appropriate group
- [x] (Maria) Set up new user account if applicable
- [x] (Maria) Give user account access to shoulder
- [x] (Maria) Notify user that shoulder is ready for use

**Comment by rushirajnenuji** [comment]
@mariagould 
```
Testing...
success: ark:/99999/fk4rv1wh7q
success: doi:10.5072/FK29W0JK2T | ark:/b5072/fk29w0jk2t
```
