### ISSUE TITLE
Few scripts need fix after migrating to Git

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/ezid-service#109]
Few scripts need a fix after migrating to Git. These are the scripts designed to assist in day-to-day operations. So far I've identified 2 issues:

- [ ] Modify deploy script to use git workflow
- [ ] EZID `client.Version` - tells the versioning of the code deployed on the instance.

**Comment by mariagould** [comment]
No longer relevant as we will be handling deployment via Travis
