### ISSUE TITLE
Create new super-shoulder: Phoebe A. Hearst Museum of Anthropology

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#113]
**Form data**
EZID prefix/shoulder: doi:10.34939/
Account/organization username (login): hearstmuseum
Shoulder display name: Phoebe A. Hearst Museum of Anthropology
Datacenter: CDL.UCB

**Note**
This is a replacement for the user's existing super-shoulder 10.21239/. 

**Steps (once request has been received and triaged by Maria)**
- [x] (Rushiraj) Run "Procedure for adding, modifying, and installing shoulders" as documented in README
- [x] (Rushiraj) Assign issue to Maria when procedure is complete
- [x] (Maria) Add new shoulder to appropriate group
- [x] (Maria) Set up new user account if applicable
- [x] (Maria) Give user account access to shoulder
- [x] (Maria) Notify user that shoulder is ready for use

**Comment by rushirajnenuji** [comment]
Hi @mariagould  - this shoulder is now ready. Thanks!
