### ISSUE TITLE
Test out DataCite 4.3 support in EZID API

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#122]
This is an exploratory/preparatory step to determine the best approach to upgrade to 4.3 and ultimately to 5.0. [Link to notes doc](https://docs.google.com/document/d/1W50Vm45oK0Klbpl48ZNaOY7ZlEcue2ZXzEAtCyPhaz8/edit)

**Our first set of steps:**

- [x] Add 4.1 schema file to ezid directory (https://schema.datacite.org/meta/kernel-4.1/)

- [x] update datacite parsing script so it can handle the new fields 

- [x] re-register an existing DOI under the new schema

**Real DOIs we can work with (previously used for testing by Dryad)**

- doi:10.18737/D7K01R
- doi:10.18737/D7PP4Q

**Comment by rushirajnenuji** [comment]
HI @mariagould  - this is now complete. The work is committed to a feature branch: `feature-datacite-schema-4.1` on Github. 

- [ ] Deploy `feature-datacite-schema-4.1` branch to stage for thorough testing. 

Also, I'll open up a new ticket for 4.3 upgrades.

**Comment by rushirajnenuji** [comment]
Completed testing for DataCite Schema 4.3
Detailed test document found here: [gist](https://gist.github.com/rushirajnenuji/ac1163a0b069968a76460eeffd24b6de)
