### ISSUE TITLE
Delete 2 ARK identifiers

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#126]
User experienced system issues when registering ARK and accidentally created 3. We should delete 2 and keep 1.

User: uci-exonerate

Keep:
ark:/88112/x2h01h

Delete:
ark:/88112/x2rg6d
ark:/88112/x2ms34

**Comment by rushirajnenuji** [comment]
Deleted both the identifiers:
`ark:/88112/x2rg6d`
`ark:/88112/x2ms34`
