### ISSUE TITLE
Batch delete: cdldmptool ARKs

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#143]
DMPTool used to use LDAP authentication for users a long time ago and they minted ARKs associated with these user accounts. This is no longer current practice and the public ARKs contain information that should be deleted. DMPTool team has signed off on this approach.

**To do:**

- [x] Rushiraj: Delete all ARKs associated with the user account `cdldmptool`.  There are 6713 ARKs. 

Example: ark:/99166/p9d21rk8k

**Important**: this is about the USER ACCOUNT `cdldmptool`. It does NOT involve any ARKs associated with the user account `dmptool`. 

- [x] Maria: Once the ARKs are deleted, unhook any shoulders from the user account and delete the account and group

**Comment by rushirajnenuji** [comment]
Steps performed:

1. Unhook the shoulder from the user.
2. Disable user log in 
3. Remove user `cdldmptool` from the group `cdl`
4. Delete user and all their identifiers
