### ISSUE TITLE
Transfer pittezid group to DataCite

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#16]
Prefixes:

- Pitt Project Tycho (doi:10.25337/)

- Pitt Quantum Repository (doi:10.17614/)

- Pitt QUBES (doi:10.25334/)

- University of Pittsburgh (doi:10.18117/)

NAAN:

- ark:/88117/p7

- ark:/87614/q6

- ark:/87269/t9

EZID Group: pittezid
EZID accounts: All (4 users total within pittezid group)

DataCite data center: CDL.PITT & CDL.PQR

They have 0 ARKs; 1 reserved DOI (https://doi.org/10.25334/Q4N711).

**Comment by mariagould** [comment]
- [ ] 1. Disable user account(s) (Maria)

- [ ] 2. Move identifiers (DataCite/Crossref)

- [ ] 3. Delete datacenter in Fabrica (Maria)

- [ ] 4. “Unhook" shoulders from EZID user(s) and group (Rushiraj)

- [ ] 5. Run “delete user” script (Rushiraj) (this will delete the identifiers)

- [ ] 6. Delete group if last user in group (Rushiraj)

- [ ] 7. Remove datacenter in master_shoulders.txt (if no longer in use) (John)

- [ ] 8. If a shoulder is no longer meant to be used to create new ids by this user or any other user, remove minter, if any. (John)

- [ ] 9. Move shoulder and datacenter entries from master_shoulders.txt to former_shoulders.txt. (John)

- [ ] 10. Move NAAN entry, if relevant, from master_naans to former_naans. (John)

- [ ] 11. Add NAAN, as relevant (copied from previous step), to end of commented recycling list near top of former_naans. (John) 

- [ ] 12. Remove client from (a) EZID-L mailing list, (b) client list at https://ezid.cdlib.org/learn/#02, (c) Crossref notification emails, as appropriate (Maria)

**Comment by mariagould** [comment]
@rushirajnenuji this is ready to work on!

**Comment by rushirajnenuji** [comment]
Hi @jkunze  - testing that you're getting notifications or not. 
Also - I just assigned this ticket to you to perform shoulder management tasks. Thanks!

**Comment by jkunze** [comment]
Done.

**Comment by mariagould** [comment]
Will be updating client list on website as part of bulk static page update. Everything else is done.
