### ISSUE TITLE
Delete ARK for UCSF IDL

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#170]
UCSF account ucsf-idl created an ARK in error and is requesting that we delete it:

ark:/88122/record_key

**Comment by mariagould** [comment]
It looks as though this may have already been deleted. @rushirajnenuji can you confirm?

**Comment by rushirajnenuji** [comment]
Okay, looks like this identifier has been deleted. I vaguely remember doing this sometime back. I might have not closed this ticket then. Closing it now.
