### ISSUE TITLE
Disable stats to CDL Dashboard

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid-service#174]
There is a cron job that runs monthly on the 2nd day of the month which sends stats to the CDL Dashboard.  

https://intracdl.cdlib.org/dashboard/cdl_dashboard/IdentifiersEZID_v2.html

We no longer want to display EZID stats here, so we should disable the cron job and inform the CDL Website team to remove EZID

- [x] Rushiraj to do: Disable cron job

- [ ] Maria to do: Once cron job is disabled, tell web team to remove EZID stats

**Comment by marisastrong** [comment]
# Monthly statistics
0 3 2 * * /apps/ezid/apps/apache/ezid/SITE/PROJECT/tools/dashboard https://intracdl.cdlib.org

**Comment by marisastrong** [comment]
CDL will no longer support the CDL Dashboard so @rushirajnenuji  can go ahead and disable the cron job which sends information to it and be finished with this task.

**Comment by rushirajnenuji** [comment]
Thank you @marisastrong. I've disabled the cronjob from the production VM.

**Comment by mariagould** [comment]
Closing. Cron job is disabled and web team is planning to sunset this page.
