### ISSUE TITLE
Fix validation for multiple diagnostic elements in Crossref DOIs

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#177]
EZID's diagnostic checks are erroring out with some preprints because preprint records include multiple diagnostic elements and EZID was not initially designed to support this. Crossref does not treat this as an error but EZID flags it. This currently affects a number of preprint DOIs. 

_Proposed solution: _ Update the validation process for preprints so EZID does not interpret multiple diagnostic elements as an error. 

- [ ] Set up on Dev and verify that validation is working 
- [ ] Set up on Stage and verify that validation is working 
- [ ] Ask Preprints team to test on Stage (identify a subset of DOIs to test)
- [ ] Move to EZID prod

**Comment by rushirajnenuji** [comment]
Update validation for the XML object:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<doi_batch_diagnostic status="completed" sp="ds3.crossref.org">
   <submission_id>1487871720</submission_id>
   <batch_id>807be0dc-61ca-11eb-ab55-0aaca0e19d37</batch_id>
   <record_diagnostic status="Success">
      <doi>10.31223/X5288T</doi>
      <msg>Possible preprint/VoR pair, Vor DOI: 10.1061/(ASCE)HY.1943-7900.0001507</msg>
   </record_diagnostic>
   <record_diagnostic status="Success">
      <doi>10.31223/X5288T</doi>
      <msg>Successfully added</msg>
   </record_diagnostic>
   <batch_data>
      <record_count>2</record_count>
      <success_count>2</success_count>
      <warning_count>0</warning_count>
      <failure_count>0</failure_count>
   </batch_data>
</doi_batch_diagnostic>
```
