### ISSUE TITLE
Add support for Crossref schema v5

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#178]
EZID currently supports Crossref schema version 4x. Version 5x of the schema is now available for deposits and EZID needs to be able to support DOIs registered using this schema. 

The schema documentation is available here:

- https://data.crossref.org/schemas/crossref5.3.1.xsd
- https://data.crossref.org/reports/help/schema_doc/5.3.1/index.html

EZID needs to continue to support older versions of the schema. Users will need to specify the version when they make a deposit.

**Comment by rushirajnenuji** [comment]
Crossref Difference: [5.1 v 5.3](https://www.diffchecker.com/gBRRaWlw)

**Comment by mariagould** [comment]
Summary of changes between 4.4.2 and 4.8.1:

-     refactoring of schema
-     relax regex rules for email addresses
-     allow ISBN beginning with 979
-     update imported JATS schema to v. 1.3
-     relax regex rules for <given_name> element\

Summary of changes between 4.8.1 and 5.3.1 (latest version):

-     replace tag with to support new affiliations structure
-     add <institution_id> element to support ROR and other org IDs
-     make either <institution_id> or <institution_name> required within
-     relax regex rules for <given_name> element

Crossref supports versions back to 4.3.0

**Comment by mariagould** [comment]
Completed in 2022
