### ISSUE TITLE
Move bioCADDIE to maintenance account

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#198]
**Account information**

Shoulders:
`ark:/57799/b9`
`ark:/57799/`

EZID user:
`biocaddie`
`biocaddie-api`

EZID group(s): `biocaddie`

Number of ARKs: 47,146

- [x] Temporarily disable login 

- [x] Move PIDs to cdl_nonpaying group (Rushiraj)

- [x] Move user(s) to `cdl_nonpaying group` (Rushiraj)

- [x] Rename the original group to *_nonpaying (Rushiraj)

- [x] Re-enable user login (Rushiraj)

- [x] Deactivate shoulder(s) (Rushiraj)

**Comment by rushirajnenuji** [comment]
Moved the account to maintenance mode. Deactivated shoulders.
