### ISSUE TITLE
Remove Perry's email from link checker notification emails

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#202]
Perry Willett retired from CDL nearly 2 years ago but his email address has recently been bcc'd on some link checker notification emails, which causes them to bounce.

We need to determine where Perry's email is being stored (there may be multiple places) and remove it from the list of notification recipients. 

Analysis from Ashley in the attached screenshot. ![Screen Shot 2021-04-13 at 12.45.17 PM.png](https://images.zenhubusercontent.com/5d7be665d6bc2d0001f77a8f/5a7366d6-f4ec-4035-95f1-0efd2672a366)

**Comment by rushirajnenuji** [comment]
Updated the user account and removed the realm admin privileges from the DB.
