### ISSUE TITLE
Clean up Merritt ARKs in Perry's account

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#217]
There are 50 ARKs associated with Merritt users that the Merritt team wants to delete. The ARKs to be deleted are listed below. They are all associated with the user account `pwillett`. There are an additional 140 ARKs in this account that should not be deleted. These remaining ARKs need to be transferred to user `elopatin` because `pwillett` is no longer active.

To summarize:

- [x] Delete the 50 ARKs below

- [x] Move all remaining ARKs (140 total) associated with user `pwillett` to user `elopatin`

- [ ] Delete user `pwillett`

**ARKs to be deleted**
1. ark:/99166/p9057cs6b
2. ark:/99166/p9057ct0w
3. ark:/99166/p9086365k
4. ark:/99166/p9154dp6k
5. ark:/99166/p91v5bh78
6. ark:/99166/p91z41w6n
7. ark:/99166/p92z12q03
8. ark:/99166/p93x83m0s
9. ark:/99166/p93x83m37
10. ark:/99166/p94x54h1h
11. ark:/99166/p95q4rm4m
12. ark:/99166/p96688m2h
13. ark:/99166/p96m33845
14. ark:/99166/p96q1sh4v
15. ark:/99166/p9707wp36
16. ark:/99166/p9707wp4p
17. ark:/99166/p97d2q78z
18. ark:/99166/p97p8td51
19. ark:/99166/p98911r0f
20. ark:/99166/p98p5v958
21. ark:/99166/p9bg2h99g
22. ark:/99166/p9bg2hc8w
23. ark:/99166/p9br8mg8h
24. ark:/99166/p9db7vq2r
25. ark:/99166/p9df6k38x
26. ark:/99166/p9dj58j8p
27. ark:/99166/p9f766730
28. ark:/99166/p9g737437
29. ark:/99166/p9gh9b93r
30. ark:/99166/p9h708120
31. ark:/99166/p9j38kh9b
32. ark:/99166/p9m03xx63
33. ark:/99166/p9mw28f4k
34. ark:/99166/p9n29p802
35. ark:/99166/p9td9n833
36. ark:/99166/p9v698f6g
37. ark:/99166/p9vd6p52v
38. ark:/99166/p9vh5cj6n
39. ark:/99166/p9w950q0p
40. ark:/99166/p9wd3q21m
41. ark:/99166/p9wp9t70n
42. ark:/99166/p9z60c269
43. ark:/99166/p9zp3w24h
44. ark:/99166/p9pr7mv09
45. ark:/99166/p9q814t08
46. ark:/99166/p9qn5zb9k
47. ark:/99166/p9rn30777
48. ark:/99166/p9rn30847
49. ark:/99166/p9rx93d7r
50. ark:/99166/p9sb3x10j

**Comment by mariagould** [comment]
There are 50 ARKs associated with Merritt users that the Merritt team wants to delete. The ARKs to be deleted are listed below. They are all associated with the user account `pwillett`. There are an additional 140 ARKs in this account that should not be deleted. These remaining ARKs need to be transferred to user `elopatin` because `pwillett` is no longer active.

To summarize:

- [ ] Delete the 50 ARKs below

- [ ] Move all remaining ARKs (140 total) associated with user `pwillett` to user `elopatin`

- [ ] Delete user `pwillett`

**ARKs to be deleted**
1. ark:/99166/p9057cs6b
2. ark:/99166/p9057ct0w
3. ark:/99166/p9086365k
4. ark:/99166/p9154dp6k
5. ark:/99166/p91v5bh78
6. ark:/99166/p91z41w6n
7. ark:/99166/p92z12q03
8. ark:/99166/p93x83m0s
9. ark:/99166/p93x83m37
10. ark:/99166/p94x54h1h
11. ark:/99166/p95q4rm4m
12. ark:/99166/p96688m2h
13. ark:/99166/p96m33845
14. ark:/99166/p96q1sh4v
15. ark:/99166/p9707wp36
16. ark:/99166/p9707wp4p
17. ark:/99166/p97d2q78z
18. ark:/99166/p97p8td51
19. ark:/99166/p98911r0f
20. ark:/99166/p98p5v958
21. ark:/99166/p9bg2h99g
22. ark:/99166/p9bg2hc8w
23. ark:/99166/p9br8mg8h
24. ark:/99166/p9db7vq2r
25. ark:/99166/p9df6k38x
26. ark:/99166/p9dj58j8p
27. ark:/99166/p9f766730
28. ark:/99166/p9g737437
29. ark:/99166/p9gh9b93r
30. ark:/99166/p9h708120
31. ark:/99166/p9j38kh9b
32. ark:/99166/p9m03xx63
33. ark:/99166/p9mw28f4k
34. ark:/99166/p9n29p802
35. ark:/99166/p9td9n833
36. ark:/99166/p9v698f6g
37. ark:/99166/p9vd6p52v
38. ark:/99166/p9vh5cj6n
39. ark:/99166/p9w950q0p
40. ark:/99166/p9wd3q21m
41. ark:/99166/p9wp9t70n
42. ark:/99166/p9z60c269
43. ark:/99166/p9zp3w24h
44. ark:/99166/p9pr7mv09
45. ark:/99166/p9q814t08
46. ark:/99166/p9qn5zb9k
47. ark:/99166/p9rn30777
48. ark:/99166/p9rn30847
49. ark:/99166/p9rx93d7r
50. ark:/99166/p9sb3x10j

**Comment by rushirajnenuji** [comment]
I ran into an issue with deleting the `pwillett` user where identifiers are not being deleted properly, I can bypass that and delete the user directly from the database but I'm keeping this ticket open because this will be helpful to debug and test once we have the resolution in place. I'll file a bug ticket in EZID repository and link it on here for reference.

**Comment by mariagould** [comment]
@rushirajnenuji I believe all of these IDs have now been deleted and the background job issue preventing deletion of the user account has now been resolved. If this is in fact the case, can we go ahead and delete the user account now? Thanks!

**Comment by rushirajnenuji** [comment]
Completed
