### ISSUE TITLE
DOI registration form: Update resource types for DataCite DOIs

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#220]
When users register a DOI with DataCite, they need to specify a resource type ("Resource Type General"). In the UI registration form, users select the resource type from a dropdown list. There are 14 existing options in the dropdown (see screenshot). There are 14 additional types that are now available in the latest version of the schema, so we need to add these to the dropdown list. 

New additions are indicated in bold in the list below. The other items are already available in the current dropdown. 

Note: For resource types with more than one word (e.g., "Interactive Resource"), these should be formatted differently in the metadata sent to DataCite so that spaces are removed. In other words, the item in the list would be presented as "Interactive Resource", but in the metadata it should be "InteractiveResource" (i.e., no spaces). 

Audiovisual
**Book**
**Book Chapter**
Collection
**Computational Notebook**
**Conference Paper**
**Conference Proceeding**
**Data Paper**
Dataset
**Dissertation**
Event
Image
Interactive Resource
**Journal**
**Journal Article**
Model
**Output Management Plan**
**Peer Review**
Physical Object
**Preprint**
**Report**
Service
Software
Sound
**Standard**
Text
Workflow
Other
![Screen Shot 2021-08-16 at 3.50.52 PM.png](https://images.zenhubusercontent.com/5d7be665d6bc2d0001f77a8f/3c42f13c-75d4-4a40-a5e0-05b5257e13d0)

**Comment by mariagould** [comment]
Places where this needs to be updated:
1. UI form itself
2. Validator
3. Search
4. Schema.org
5. Dublin Core

**Comment by rushirajnenuji** [comment]
completed as part of [v2.0.5](https://github.com/CDLUC3/ezid/releases/tag/2.0.5) release.
