### ISSUE TITLE
Update DataCite resource types mapping to Dublin Core

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#225]
EZID maps DataCite resource types to Dublin Core. We need to update the mapping to include the new resource types that DataCite has added in its latest schema release, which we are now adding to the EZID registration form.

To do:

- [ ]  Rushiraj: Add current list to this ticket

- [ ]  Maria: Determine what the new mappings should be

- [ ]  Rushiraj: Update the mappings list

**Comment by rushirajnenuji** [comment]
```
_dublinCoreTypes = {
    "collection": "Collection",
    "dataset": "Dataset",
    "event": "Event",
    "image": "Image",
    "interactiveresource": "InteractiveResource",
    "movingimage": "Audiovisual",
    "physicalobject": "PhysicalObject",
    "service": "Service",
    "software": "Software",
    "sound": "Sound",
    "stillimage": "Image",
    "text": "Text",
}
```

**Comment by rushirajnenuji** [comment]
completed as part of [v2.0.5](https://github.com/CDLUC3/ezid/releases/tag/2.0.5) release.
