### ISSUE TITLE
Report of International Journal of Comparative Psychology DOIs

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#227]
I need a report of all DOIs registered in EZID for the International Journal of Comparative Psychology. These are Crossref DOIs and they use the shoulder doi:10.5070/P4. So the report should be the results of a query for all DOIs that have this shoulder. 

The report needs to include:
DOI, Title, Author list, Publication date

**Comment by rushirajnenuji** [comment]
[gist](https://gist.github.com/rushirajnenuji/ed86824134b0547dddda15452172e9c3)

**Comment by mariagould** [comment]
@rushirajnenuji is it possible to get any of the metadata associated with these DOIs, like title or author name? I need to identify the DOIs in the list that are duplicates of existing ones (registered on a different shoulder) so having additional metadata would help run a comparison.

**Comment by rushirajnenuji** [comment]
Hey @mariagould  - yes that should be easy, I'll retrieve the records from our database and get back to you. I'll post a gist over here soon.

**Comment by rushirajnenuji** [comment]
[Link to the Gist](https://gist.github.com/rushirajnenuji/8e7aa9705ddd4895bd60234d575ab278)
