### ISSUE TITLE
Delete 6 shoulders

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#229]
These shoulders were recently created in error. They need to be permanently deleted as they will not be used. 

`ark:/42409/ac`	Penn State Libraries - Access
`ark:/42409/pr`	Penn State Libraries - Dark Preservation
`ark:/42409/ed`	Penn State Libraries - Educational Resource
`ark:/42409/ex`	Penn State Libraries - Exhibitions
`ark:/42409/fa`	Penn State Libraries - Finding Aids
`ark:/42409/t`	Penn State Libraries - Testing

Note that I ran the `shoulder-deactivate` command on `42409/t`. This was just to test the deactivate functionality.

**Comment by rushirajnenuji** [comment]
completed DB operations as required
