### ISSUE TITLE
Transfer ownership of a DOI

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#230]
We need to transfer ownership of a DOI so that it can be managed by the UCSD Library going forward. The group that initially created the DOI is no longer active.

DOI to be transferred: https://doi.org/10.7269/p3mg7mdz 

Current owner: ESIPCommon

New owner: ucsd_lib

**Comment by rushirajnenuji** [comment]
the identifier now reflects the updated owner
