### ISSUE TITLE
Batch status change for JHU ARKs 

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#239]
JHU is canceling their EZID ARK service (see #218). The ARKs that they registered no longer resolve because the project they are associated with has been sunset. They have requested that we perform a batch operation on their behalf to change the status of all of their ARKs to "unavailable." 

This task should be completed after performing #218. 

- ARKs to change: all ARKs associated with user 'jhudms'
- Task: set identifier status to "unavailable" and add the following message to appear on tombstone page for each identifier: “The RMap project has been retired and all related services have been shut down.”

**Comment by jsjiang** [comment]
Completed
