### ISSUE TITLE
Change status of PISCO test DOIs

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#242]
The PISCO service created a number of test DOIs in production that are throwing errors when a user attempts to resolve them. 

DOIs should not be deleted; therefore the status should be changed to "unavailable." This may not prevent further errors from occurring but if it becomes a more frequent issue we will escalate to DataCite to see if we can remove them from the handle system. 

To do: Set to "unavailable" the test DOIs identified in the below file (2023 DOIs in total).

[pisco-dois.xlsx](https://github.com/CDLUC3/ezid-service/files/9294290/pisco-dois.xlsx)

**Comment by mariagould** [comment]
Waiting for confirmation from PISCO team to remove the test identifiers.

**Comment by mariagould** [comment]
PISCO team has confirmed we can move forward with changing the status of these test identifiers. I have updated the file attached above to make the list easier to retrieve.

**Comment by rushirajnenuji** [comment]
Looks like this ticket was completed on/around `2022-08-15 17:XX:XX UTC` but never closed. Sorry for this oversight. I randomly checked a few DOIs from the above list, and they all return `unavailable` status. Closing this ticket as no more actions are required here.
