### ISSUE TITLE
Update DataCite relation types in EZID UI

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#247]
**Background:**
A user reported that some of the relation type options available in DataCite for identifying relationships between DOIs and other identifiers are not available in the EZID UI. The specific relationship the user was looking for was "isVersionOf". The user confirmed that the relationship type can be added when registering a DOI via the API, so this issue seems to be limited to the UI. 

When I investigated further, I confirmed that this relationship type is not available in the dropdown list of relation types in the UI (screenshot). 

![Screen Shot 2022-11-29 at 2 32 10 PM](https://user-images.githubusercontent.com/45110557/204685276-692db407-7eb5-426b-bfe6-38bd7f1360a7.png)

I then compared what we have in EZID with the full list of relation types supported in the latest schema version, and identified others that are missing. There are 9 relation types missing in total from the UI dropdown, which means that users registering DOIs via the UI cannot take advantage of these relation types. It also means that if a user successfully registers a DOI via the API with one of the missing types, if the user then uses the UI to make subsequent changes, they will see a validation error, as shown below in the example for https://doi.org/10.6075/J09P31TF. 

![Screen Shot 2022-11-29 at 5 27 55 PM](https://user-images.githubusercontent.com/45110557/204685102-e2a7edfe-d803-4dd9-9df1-27fce8a917b8.png)

**Explanation for this situation:**
It appears that the missing relation types were added to the schema in recent versions (4.1, 4.2, and 4.4). When the EZID UI was updated to support the new schema versions, the new relation types were overlooked. 

**Proposed resolution:**
Add the nine missing relation types to the dropdown list in the UI, in the "related identifier" section. No other UI changes should be required. 

**Missing relation types to add:**

1. IsDescribedBy (display as `Is Described By`) *(added in schema version 4.1)*
2. Describes *(added in schema version 4.1)*
3. HasVersion (display as `Has Version`) *(added in schema version 4.1)*
4. IsVersionOf (display as `Is Version Of`) *(added in schema version 4.1)*
5. IsPublishedIn (display as `Is Published In`) (added in schema version 4.4)
6. IsRequiredBy (display as `Is Required By`) *(added in schema version 4.1)*
7. Requires *(added in schema version 4.1)*
8. IsObsoletedBy (display as `Is Obsoleted By`) *(added in schema version 4.2)*
9. Obsoletes *(added in schema version 4.2)*

**Additional requirements:**

- [x] The new relation types should be inserted in alphabetical order in the existing dropdown
- [x] The display text for the relation type should include spaces in multi-word terms, and no spaces when the metadata is sent to DataCite

**Comment by rushirajnenuji** [comment]
Deployed a fix in [v3.0.14](https://github.com/CDLUC3/ezid/releases/tag/3.0.14)
