### ISSUE TITLE
Delete duplicate Crossref DOIs from EZID

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#255]
eScholarship mistakenly registered a number of duplicate DOIs for a journal that already had DOIs. These DOIs failed in Crossref because they were identified as duplicates.  

eScholarship has addressed the necessary issues on their end for the original article DOIs to resolve. 

The DOIs that were mistakenly registered in EZID need to be deleted since they are not being used, were never registered with Crossref, and will never resolve. 

The list of DOIs to be deleted (n=728) is here: https://gist.github.com/rushirajnenuji/5598a9056a8fc192c12748f6df49afda.

**Comment by jsjiang** [comment]
Completed
