### ISSUE TITLE
Comparison check: Q4 2019

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#32]
https://confluence.ucop.edu/display/DataCite/EZID+Operations#EZIDOperations-comparing-systems

**Comment by rushirajnenuji** [comment]
I thought this should not take a long time, but while going through the documentation I found an interesting comment from Greg: `A recent change to the DataCite API has made this script take several days;`

I've started the DataCIte comparison on my end. I will keep the issue updated with the progress.

**Comment by rushirajnenuji** [comment]
Closing this ticket. Check the issue linked above for additional progress on the comparison checks. (issue # 111)
