### ISSUE TITLE
Move shoulder management into EZID

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#33]
[Notes doc](https://docs.google.com/document/d/1eWT3xxtftFCQMUJ6UyOvcpqb2rIRPJ86zs4623kiuak/edit)

**New workflow:**

1. Liaison/admin requests a new shoulder (via Google Form) and provides details about what they need (ARKs or DOIs, etc.)
2. Maria receives request and determines course of action depending on what is requested
- NAAN: Fill out NAAN request form (https://n2t.net/e/naan_request) on behalf of user
- DataCite prefix: Assign new prefix in Fabrica from list of available prefixes
- Crossref prefix: Email Crossref to request new prefix

3. Maria chooses a short shoulder if user has not requested a specific one (follow existing conventions at https://ezid.cdlib.org/learn/id_concepts)
- Default shoulder selection: pick one letter and one digit (not 0 or 1).
- To pick letter (for DOI or ARK shoulder), start with a non-vowel, non-ell (inflexible) letter from the org acronym.
- To pick the DOI shoulder digit, start with last prefix digit (flexible)
- To pick the ARK shoulder digit, start with second to last prefix digit (flexible)

4. Maria set up Github issue using new account/shoulder template and assign to Rushiraj

5. Rushiraj runs a script to generate the shoulder entry on EZID

_>>To do before new workflow can be implemented:_ 
- [x] John to combine make-account/make-shoulder scripts into new script
- [x] New script needs to live in shoulders directory (home directory) - John to set it up
- [x] Perhaps in the future, move to tools directory (decide on this later)

6. Rushiraj runs ./install-shoulders and ./reload-all in EZID to install in stg and prod
_>>To do before new workflow can be implemented:_ 
- [x] One-off task: Rushiraj make change so that EZID load pulls shoulders from EZID instead of N2T
- [x] One-off task: Rushiraj to test shoulder installation script
- [x] Need to check if EZID’s existing reload and reload-all scripts are the same as ones in N2T or different (if different, do they need to be renamed?) - Rushiraj to investigate and compare

7. Rushiraj notifies Maria that shoulder is ready

8. Maria configures shoulder/account in EZID
- Add new shoulder to appropriate group
- Set up new user account if applicable
- Give user account access to shoulder

9. Maria notifies user that shoulder is ready

**Comment by mariagould** [comment]
FYI, I've updated this issue with our proposed workflow and identified the follow-up tasks related to adapting the current scripts.

**Comment by mariagould** [comment]
Question for @jkunze - what about the shoulders that were previously created? Can/should we move these entries into EZID? I'd appreciate your thoughts.

**Comment by jkunze** [comment]
All the old and new shoulders live together as a package in the shoulder database (file) that we're moving to EZID. There's no separating them. Just a reminder, however, that the current end game for now will have all shoulder _minters_ (old and new) continuing to live on N2T, not because anybody likes it that way, but because it's a bunch more work. Maybe one day.

**Comment by mariagould** [comment]
> All the old and new shoulders live together as a package in the shoulder database (file) that we're moving to EZID. There's no separating them. Just a reminder, however, that the current end game for now will have all shoulder _minters_ (old and new) continuing to live on N2T, not because anybody likes it that way, but because it's a bunch more work. Maybe one day.

@jkunze thanks. And we'll be tackling the minter situation (eventually) via https://github.com/CDLUC3/ezid-service/milestone/22

**Comment by mariagould** [comment]
Next question for @jkunze and maybe @rushirajnenuji : I'm assuming that with the new workflow I will no longer need to enter the account details in the new account worksheet in EZID admin?

**Comment by jkunze** [comment]
That should be achievable, at least for what my tasks are.

**Comment by mariagould** [comment]
@jkunze can you please take a look at the to-do items in Step 5 and let us know if they are completed yet? Thanks!

**Comment by jkunze** [comment]
Step 5b completed, step 5a started.
5c will just need a conversation between Rushiraj an me.

**Comment by rushirajnenuji** [comment]
Completed 6a today. Tested on Stage. (see ticket number 80 linked above)
> One-off task: Rushiraj make change so that EZID load pulls shoulders from EZID instead of N2T

TODO: Deploy the change in production.

Working on 6c. This is the only remaining part of this ticket.
