### ISSUE TITLE
Transfer Potato Center to DataCite

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#37]
**Account information**
Prefix(es): 10.21223
EZID account name(s): International Potato Center
EZID Group(s): cdl_nonpaying
DataCite data center(s): n/a
Number of DOIs (number reserved): 258 public, 65 reserved
Number of ARKs: 0

**Steps**
- [x] 1. Disable user account(s) (Maria)

- [x] 2. Move identifiers (DataCite/Crossref)

- [x] 3. Delete datacenter in Fabrica (Maria)

- [x] 4. “Unhook" shoulders from EZID user(s) and group (Rushiraj)

- [x] 5. Run “delete user” script (Rushiraj) (this will delete the identifiers)

- [x] 6. Delete group if last user in group (Rushiraj) *note - do not delete for this one!*

- [x] 7. Remove datacenter in master_shoulders.txt (if no longer in use) (John)

- [x] 8. If a shoulder is no longer meant to be used to create new ids by this user or any other user, remove minter, if any. (John)

- [x] 9. Move shoulder and datacenter entries from master_shoulders.txt to former_shoulders.txt. (John)

- [x] 10. Move NAAN entry, if relevant, from master_naans to former_naans. (John)

- [x] 11. Add NAAN, as relevant (copied from previous step), to end of commented recycling list near top of former_naans. (John) 

- [x] 12. Remove client from (a) EZID-L mailing list, (b) client list at https://ezid.cdlib.org/learn/#02, (c) Crossref notification emails, as appropriate (Maria)

**Comment by mariagould** [comment]
DataCite is moving these via batch transfer Wednesday September 25.

**Comment by mariagould** [comment]
Hi @rushirajnenuji this is a transfer to DataCite from a client that we previously moved into a maintenance account under the cdl_nonpaying group. DataCite has moved the identifiers so we can remove them in EZID. Let me know if you have any questions.

**Comment by mariagould** [comment]
@jkunze I think this is still waiting on you.

**Comment by jkunze** [comment]
Thanks for the nudge! It's done now.

I guess the email alert for this arrived during the first day of Force 2019, then I forgot all about it and missed the reminder, which, if I look carefully, is front and center in the noisy github page (maybe you can you tell I'm not a fan of the UI :).
