### ISSUE TITLE
Transfer ImmPort to DataCite

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#38]
**Account information**
Prefix(es): doi:10.21430/M3
NAAN(s): ark:/81430/p4
EZID account name(s): UCSF ImmPort
EZID Group(s): UCSF
DataCite data center(s): CDL.UCSF
Number of DOIs (number reserved): 394 (0 reserved)
Number of ARKs: 0

**Steps**
- [x] 1. Disable user account(s) (Maria)

- [x] 2. Move identifiers (DataCite/Crossref)

- [x] 3. Delete datacenter in Fabrica (Maria)

- [x] 4. “Unhook" shoulders from EZID user(s) and group (Rushiraj)

- [x] 5. Run “delete user” script (Rushiraj) (this will delete the identifiers)

- [x] 6. Delete group if last user in group (Rushiraj)

- [x] 7. Remove datacenter in master_shoulders.txt (if no longer in use) (John)

- [x] 8. If a shoulder is no longer meant to be used to create new ids by this user or any other user, remove minter, if any. (John)

- [x] 9. Move shoulder and datacenter entries from master_shoulders.txt to former_shoulders.txt. (John)

- [x] 10. Move NAAN entry, if relevant, from master_naans to former_naans. (John)

- [x] 11. Add NAAN, as relevant (copied from previous step), to end of commented recycling list near top of former_naans. (John) 

- [x] 12. Remove client from (a) EZID-L mailing list, (b) client list at https://ezid.cdlib.org/learn/#02, (c) Crossref notification emails, as appropriate (Maria)
@

**Comment by mariagould** [comment]
This transfer is ready to be worked on whenever you are ready.

**Comment by mariagould** [comment]
@rushirajnenuji did you unhook the shoulders from the group? Just wondering why we might be getting the recent error that just came in.

**Comment by rushirajnenuji** [comment]
Hey @mariagould  and @jkunze - I did unhook the shoulders `ark:/81430/p4` and `doi:10.21430/M3` from the user `UCSF Immiport` but the shoulder is currently in used by another user `UCSF`. In that case, I'm not sure that steps to delete the shoulder are required.

**Comment by mariagould** [comment]
@rushirajnenuji my guess is it's probably showing as in use by `UCSF` because this is the parent group. The shoulder should be unhooked from the group as well.

**Comment by rushirajnenuji** [comment]
<img width="660" alt="Screen Shot 2019-10-21 at 2 10 29 PM" src="https://user-images.githubusercontent.com/19696935/67243508-8f271980-f40c-11e9-9c84-8cee9d253fc5.png">

Hey Maria - I also see another user `UCSF` assigned to both these shoulders. Is that user account also a parent account?

**Comment by mariagould** [comment]
Yes, it's a user account but also the group admin. It's fine to unhook.

**Comment by rushirajnenuji** [comment]
Aah cool! Removed both the shoulders from the user and the group. @jkunze sorry for the trouble. This is now ready.

**Comment by jkunze** [comment]
OK, my part is done.

**Comment by mariagould** [comment]
Transfer complete.
