### ISSUE TITLE
Move Washington State to maintenance account

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#40]
**Account information**
NAAN: ark:/87273/q8
EZID account name(s): Washington State University
EZID Group(s): washstate
EZID user: washstate
DataCite data center(s): n/a
Number of DOIs (number reserved): 0
Number of ARKs: 1426

- [x] Disable login (Maria)

- [x] If DataCite DOI, move PIDs to CDL.CDL datacenter (Maria)

- [x] Delete old client datacenter in Fabrica (if applicable) (Maria)

- [x] Move PIDs to cdl_nonpaying group (Rushiraj)

- [x] Move user to cdl_nonpaying group (Rushiraj)

- [x] Rename the original group to *_nonpaying (Rushiraj)

- [x] Add "active: false" flag to shoulder entry in master_shoulders.txt. (John)

- [x] Associate the shoulder with CDL.CDL datacenter in master_shoulders.txt (John)

- [x] Remove datacenter in master_shoulders.txt (if no longer in use) (John)

**Comment by mariagould** [comment]
Hi Rushiraj, this is an ARKs-only account that needs to be moved to maintenance status whenever you get a chance. This is similar to what we did for UMich KGrid a few months ago. I added to this issue the steps that we discussed with John when we updated the process in June. Step 3 is not relevant because it is not a DataCite DOI. And I'm not sure if Step 2 is relevant either. Let me know if you have questions. Thanks!

**Comment by rushirajnenuji** [comment]
Hi @jkunze  - Update: I've completed the _ezid_ side of things. And I've assigned this ticket to you. Thank you!

**Comment by jkunze** [comment]
@rushirajnenuji it looks like the shoulder still needs to be unhooked on your end

**Comment by mariagould** [comment]
I'm not seeing any users linked to this shoulder. Is this work complete?

**Comment by jkunze** [comment]
@rushirajnenuji I saw your email, but figured you still had something to do (but maybe was mistaken).

**Comment by mariagould** [comment]
@jkunze were you thinking there was more to do because you got an error? I'm just trying to figure out if we can close out this ticket or if there is more to be done.

**Comment by jkunze** [comment]
@mariagould that's right. I was waiting for @rushirajnenuji to tell me when/if I should try again.

**Comment by rushirajnenuji** [comment]
Hey @jkunze  - I've checked the shoulder: `ark:/87273/q8` and I didn't change anything because things looked okay from EZID end. Te shoulder has no associated users / groups in both Stage and Prod systems. Not sure the reason for this error. Could you please try this again. Thank you!

**Comment by jkunze** [comment]
Done. I marked the shoulder as inactive and reloaded about 5 mins ago. No errors so far.

**Comment by rushirajnenuji** [comment]
Thanks @jkunze.
@mariagould  - this is now complete.

**Comment by mariagould** [comment]
Thank you! Closing this out.
