### ISSUE TITLE
Plan for updating DataCite metadata to 4.3

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#58]
DataCite released version 4.3 of their schema August 2019: https://schema.datacite.org/meta/kernel-4.3/

EZID currently supports version 4.0. We need to document the tasks entailed in upgrading to 4.3

Historical context:
Switch to version 4.0 [link to epic in Pivotal](https://www.pivotaltracker.com/epic/show/2556751)

**Comment by mariagould** [comment]
@rushirajnenuji notes doc for DataCite schema research is here https://docs.google.com/document/d/1W50Vm45oK0Klbpl48ZNaOY7ZlEcue2ZXzEAtCyPhaz8/edit

**Comment by rushirajnenuji** [comment]
Thanks for the write-up, Maria. This is super helpful. I'll keep working in the same document.
