### ISSUE TITLE
New account/shoulder: KITP

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#64]
- Group: sb-library
- DataCenter: CDL.UCSB
- ARKs or DOIs? DOIs
- Crossref or DataCite DOI? DataCite
- Prefix/NAAN: 10.26081
- Desired DOI shoulder: any shoulder is fine
- Desired ARK shoulder: n/a
- Account/organization/shoulder display name: KITP
- Account/organization login: sb-kitptalks
- Primary account contact: Alina Gutierrez; Kohn Hall, University of California, Santa Barbara, CA, 93106-4030; 805-893-2896	alina@ucsb.edu
- Primary email address associated with this account: alina@ucsb.edu
- Secondary account contact (optional): Maggie Sherriffs; sherriffs@ucsb.edu; 805-893-6332	
- How are you planning to use ARKs/DOIs? Assign to recorded scientific talks for KITP programs and conferences in online repository

**Comment by mariagould** [comment]
@jkunze here is another shoulder request. Let me know if you have questions.

**Comment by mariagould** [comment]
@jkunze I assigned a different prefix that begins with 10.2, so this is ready for you now. Thanks.

**Comment by jkunze** [comment]
OK, my part's finished.

**Comment by mariagould** [comment]
Account has been set up in EZID and user has received login information.
