### ISSUE TITLE
Bug in util.py

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#65]
[via John]

The latest shoulder requests involves, for the first time, a prefix that begins 10.3..., which exposed a bug in Greg's code. This will have to be fixed before the shoulder can be created. Basically, the shadow ids that get minted start with a character from "bcdfghjkmnpqrstvwxz", but Greg's code assumes "bcdefghijklmnopqrstuvwxyz". So c corresponds to 10.1xxxx, d to 10.2xxxx, (skipping e) f to 10.3xxxx. Greg's code has f corresponding to 10.4xxxx. 

That's is a pretty brief explanation -- is it enough for you to go on to fix this?

def shadow2doi (ark):
  """
  Given a scheme-less shadow ARK identifier for a DOI (e.g.,
  "b5060/foo"), returns the corresponding scheme-less DOI identifier
  (e.g., "10.5060/FOO").  The returned identifier is in canonical
  form.
  """
  if ark[0] == "b":
    doi = "10." + ark[1:]
  else:
    doi = "10." + chr(ord("1")+ord(ark[0])-ord("c")) + ark[1:]
  return _hexDecodePattern.sub(lambda c: chr(int(c.group(1), 16)), doi).upper()

[also from John]
The letter e was skipped along with all vowels, along with the letter ell. That may sound familiar, as it's (what I call) the "betanumeric" restricted characters (bcdfghjkmnpqrstvwxz0123456789) that supports the check digit algorithm. In the early days when DOI Prefixes were 10.<4-digits>, Greg's algorithm worked for 10.1<4-digits> and 10.2<4-digits>, and maybe thought we'd never see a DOI prefix of 10.3<4-digits>.

Here's some Perl code with the correct correspondence.

# We don't check, but both args should be non-empty strings,
# the first being an NCDA-acceptable char [bcdfghjk...].
#
sub n2d { my( $chr1, $final4 )=( shift, shift );

        my $finalpart = $final4 =~ s/^0+//;     # remove 0 padding, if any
        my $firstpart =
                ($chr1 eq 'b' ? '' :
                ($chr1 eq 'c' ? '1' :
                ($chr1 eq 'd' ? '2' :
                ($chr1 eq 'f' ? '3' :
                ($chr1 eq 'g' ? '4' :
                ($chr1 eq 'h' ? '5' :
                ($chr1 eq 'j' ? '6' :
                ($chr1 eq 'k' ? '7' :
                ($chr1 eq 'm' ? '8' :
                ($chr1 eq 'n' ? '9' :
                ($chr1 eq 'p' ? '10' :
                ($chr1 eq 'q' ? '20' :
                ($chr1 eq 'r' ? '30' :
                ($chr1 eq 's' ? '40' :
                ($chr1 eq 't' ? '50' :
                ($chr1 eq 'v' ? '60' :
                ($chr1 eq 'w' ? '70' :
                ($chr1 eq 'x' ? '80' :
                ($chr1 eq 'z' ? '90' :
                                'OUTofRANGE'
        )))))))))))))))))));

        return $firstpart . $final4;
}

sub naan2doip { my $naan = shift or return '';

        # Be flexible.  Work with pure NAANs or embedded NAANs.
        # replace with a prefix what looks like a NAAN with prefix;
        # if the NAAN has no equivalent, return it untouched;
        # everything else will be untouched
        $naan =~ s
                { \b (ark:/*)? ([bcdfghjkmnpqrstvwxz]) (\w{4}) \b (\S*) }
                { "doi:10." . n2d($2, $3) . "\U$4\E" }xeg;
        $naan =~ s/%([0-9A-Fa-f]{2})/uc chr hex $1/xeg; # extra credit
        return $naan;
}

**Comment by mariagould** [comment]
FYI, I'm going to deprioritize this now that it's no longer blocking any active shoulder requests. We need to address it at some point soon but not right away.

**Comment by rushirajnenuji** [comment]
Deployed a fix for this to produciton today. 

Tested by creating a sample shoulder - it was successful.

![Screen Shot 2020-03-05 at 5 04 00 AM](https://user-images.githubusercontent.com/19696935/75984355-1dbda400-5e9f-11ea-97d3-b255135d5268.png)
