### ISSUE TITLE
Add + Update current EZID Documentation

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/ezid-service#72]
Add + Update current EZID Documentation
Things to look into:

- [x] verify that the current Operations documents reflect the new changes with the EZID Linux 2 system
- [x] add the Linux 2 + Apache 2.4 migration documentation.

**Comment by rushirajnenuji** [comment]
Hey @mariagould  - I have created this issue to work on the documentation process (relevant to the recent upgrades). I can think of two things that we need to look into. Feel free to include additional sub-tasks to this issue.

**Comment by mariagould** [comment]
Thanks @rushirajnenuji - I will think about this. My first thought is if there's anything to add about the comparison check process. I'll let you know if I think of others.

**Comment by rushirajnenuji** [comment]
Completed iteration 1 of the operations document. Added the File system and the stack set up notes on Confluence. 

ToDO:

- [ ] Notes re steps performed for migration as a one-off task.
