### ISSUE TITLE
Create new DataCite shoulder: CDL eScholarship (Supplemental Material)

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#75]
*Form data*
EZID prefix/shoulder: doi:10.34940/E2
Account/organization username (login): cdl-eschol
Shoulder display name: CDL eScholarship (Supplemental Material)
Datacenter: CDL.CDL

**Steps (once request has been received and triaged by Maria)**
- [x] (Rushiraj) Run "Procedure for adding, modifying, and installing shoulders" as documented in README
- [x] (Rushiraj) Assign issue to Maria when procedure is complete
- [x] (Maria) Add new shoulder to appropriate group
- [x] (Maria) Set up new user account if applicable
- [x] (Maria) Give user account access to shoulder
- [x] (Maria) Notify user that shoulder is ready for use

**Comment by jkunze** [comment]
@mariagould Which DOI Prefix should be used for these 11 DataCite shoulders? I'm assuming these are meant to differ from the 11 10.5070 Crossref shoulders.

Also, if they're different shoulders, the labels will have to differ. Right now it looks like they're identical.

**Comment by mariagould** [comment]
Hi @jkunze I'm still setting this up - it's not ready for anyone else to look at yet.

**Comment by rushirajnenuji** [comment]
Hey @mariagould  - this is ready! :)
