### ISSUE TITLE
New account/shoulder: LBNL National Energy Research Scientific Computing Center

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#76]
ARK or DOI? DOI
If DOI, DataCite or Crossref? DataCite
Datacenter: CDL.UCB
Account/organization display name: LBNL National Energy Research Scientific Computing Center 
Account/organization username (login): lbnl-nersc	
Prefix: 10.7933
Desired shoulder: N3
Any additional comments?

**Comment by mariagould** [comment]
This one is ready @jkunze - I streamlined the information a bit. Hopefully this is everything you need? Thanks.

**Comment by jkunze** [comment]
Done. If it has a datacenter, I guess I can assume it's a datacite prefix, not crossref, right?

**Comment by mariagould** [comment]
Correct - but I'll add that as a field in future tickets. 

Thank you!

**Comment by mariagould** [comment]
Shoulder is created and user has been notified.
