### ISSUE TITLE
Delete account: Facebase

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#77]
Facebase Consortium is canceling its EZID service. Group and user account need to be deleted. User has registered no identifiers. 

Shoulder: ark:/88119/f7
User: facebase
Group: facebase

- [x] Maria: Disable user login
- [x] Maria: Unhook shoulder from group
- [x] Maria: Delete user account
- [x] Maria: Delete group
- [x] John: Flag shoulder as inactive

**Comment by mariagould** [comment]
@jkunze the shoulder for Facebase Consortium needs to be marked as inactive in the database. I have disabled the shoulder access in EZID and deleted the group and user. 

This account had created no identifiers so our protocol is to remove the user account and group rather than move this into a maintenance status.

**Comment by jkunze** [comment]
Just to confirm, should I mark the shoulder as inactive?
(It seems possibly a case of actually removing the shoulder, its minter, and recycling the NAAN.)

**Comment by jkunze** [comment]
Tried marking it as inactive, but it generated an error on stg where it's still referenced.

**Comment by rushirajnenuji** [comment]
Hey @jkunze  - sorry I was not aware of this shoulder. You're right, it was active on Stage - I've now unhooked it from Stage so it can be deleted. Can you please try it again?

**Comment by rushirajnenuji** [comment]
@mariagould  - quick question - usually we delete groups/users via scripts that Greg had developed. Did you delete them via the UI? Was the operation successful?

**Comment by mariagould** [comment]
Sorry for the trouble/confusion @rushirajnenuji and @jkunze ! 

Re: removing groups/users - I thought I could do this myself because I do have that ability via Admin UI and thought this was how we handled a previous situation with the Caltech account. Perhaps I was mistaken and I should have only unhooked the shoulder myself and let Rushiraj handle deleting the user/group by running the scripts. Will the scripts include stage too? In any case I'm sorry for messing this up. 

Re: flagging/removing shoulders my only concern about recycling is that we have sometimes run into issues where the NAAN or prefix was inadvertently also used by other user accounts (a recent situation with UCLA & UT Austin for instance). But if we can ensure that is not the case I'm fine with recycling if that seems best.

**Comment by jkunze** [comment]
So this doesn't come back to haunt us, I've just followed protocol and marked it inactive. I'm all done with my bit now.

**Comment by rushirajnenuji** [comment]
Hey @mariagould  - sorry I was wrong!
> Re: removing groups/users - I thought I could do this myself because I do have that ability via Admin UI and thought this was how we handled a previous situation with the Caltech account. 

It looks like the deletion performed via the UI was actually successful. The user and group were deleted from the production environment. We still had those records in stage, but I went ahead and removed them from stage database as well.

**Comment by mariagould** [comment]
Thanks @rushirajnenuji. Let's discuss the optimal workflow for these types of things at our next call.
