### ISSUE TITLE
EZID load pulls shoulders from EZID instead of N2T

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#80]
Rushiraj needs to change the configuration procedure.

**Comment by mariagould** [comment]
Rushiraj needs to change the configuration.

**Comment by mariagould** [comment]
Closing as duplicate.

**Comment by rushirajnenuji** [comment]
Hey @mariagould  - I'm reopening this issue to keep track of it as a separate task. I hope that's okay!

**Comment by rushirajnenuji** [comment]
Sub task:

- [ ] Clean up reload scripts

**Comment by rushirajnenuji** [comment]
Associated with #33

**Comment by rushirajnenuji** [comment]
Solved this in the above commit. https://github.com/CDLUC3/ezid/commit/295d5eaf099650772bf6283dee80b713df5bfa72

Tested the approach on Stage and verified that it works. We can probably deploy this to production in the next cycle.

Have performed a first pass on the cleaning for the shoulder setup withing ezid. Needs some more work. But, I'll link the parent ticket #33 with those additional commits. Closing this ticket.

**Comment by rushirajnenuji** [comment]
Adding a pointer to this ticket - changes have been successfully deployed to production today!
