### ISSUE TITLE
New account/shoulder: NCEAS Dangermond Preserve

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#81]
EZID prefix/shoulder: doi:10.25497/D7
Account/organization username (login): sb-nceas
Shoulder display name: Dangermond Preserve
Datacenter: CDL.UCSB

#
Requestor name:
Campus:
Is this request for an eScholarship journal?	
(if eScholarship): Publication title:
Is this request for ARKs or DOIs?	
Primary account contact:	
Primary email address associated with this account:	
Secondary account contact (optional):
How are you planning to use ARKs/DOIs?

**Comment by mariagould** [comment]
@jkunze here is an actual (non-test) request to put through the new workflow for shoulder configuration. Let me know if you have questions.

**Comment by jkunze** [comment]
This shoulder is created and installed.
It's about halfway automated now.

**Comment by mariagould** [comment]
Thanks! Closing this out.
