### ISSUE TITLE
Create new ARK shoulder: ESS-DIVE

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#83]
EZID prefix/shoulder: ark:/78662/s2
Account/organization username (login): lbnl-essdive
Shoulder display name: Environmental System Science Data Infrastructure for a Virtual Ecosystem (ESS-DIVE)
Datacenter:

**Comment by mariagould** [comment]
This ARK shoulder is ready for you @jkunze

**Comment by jkunze** [comment]
Shoulder created.

**Comment by mariagould** [comment]
Thank you! Closing.
