### ISSUE TITLE
Create new Crossref shoulder: UCSC eScholarship

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid-service#90]
**Form data**
EZID prefix/shoulder: doi:10.5070/SC2
Account/organization username (login): ucsc-eschol
Shoulder display name: UCSC eScholarship
Datacenter: 

**Steps (once request has been received and triaged by Maria)**
- [x] (Rushiraj) Run "Procedure for adding, modifying, and installing shoulders" as documented in README
- [x] (Rushiraj) Assign issue to Maria when procedure is complete
- [x] (Maria) Add new shoulder to appropriate group
- [x] (Maria) Set up new user account if applicable
- [x] (Maria) Give user account access to shoulder
- [x] (Maria) Notify user that shoulder is ready for use

**Comment by rushirajnenuji** [comment]
Hey @mariagould  - passing this on to you...

**Comment by rushirajnenuji** [comment]
Hey @mariagould  - it looks like all the shoulder tasks for this tickets are complete. I see the shoulder assigned to the corresponding user and groups. Can we move ahead and close this ticket?

**Comment by mariagould** [comment]
Was waiting to coordinate with the account user. This communication is now complete so I am closing the ticket.
