### ISSUE TITLE
Add user documentation to EZID Client Tools

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/ezid-service#99]
This issue is specific to documentation for EZID CLient tools residing at [EZID Client tools](https://github.com/CDLUC3/ezid-client-tools)

Current situation: We do have some documentation for the EZID client tools, but it is too scattered. Part of the documentation is on EZID API while part of it is in-code documentation. It would be nice to have one complete user guide on how to use these scripts. Especially now that we have scripts that support different versions of Python - things could be a bit confusing. 

Proposal: Create better READ ME and Documentation that resides along with the code on GitHub.

**Comment by mariagould** [comment]
Closing this issue as we are trying to address documentation updates more holistically
